### ISSUE TITLE
Nested functions do not work.

### ISSUE THREAD

**Issue by Phrogz** [Phrogz/ZSS#1]
```css
tag { prop: f(g(1,2),h(3,4)) }
```
is parsed as

```lua
f(
   'g(1',
   '2)',
   'h(3',
   '4)'
)
```

Things don't go well from there.
