### ISSUE TITLE
Declarations require space after semicolon

### ISSUE THREAD

**Issue by Phrogz** [Phrogz/ZSS#2]
This rule parses correctly:

```css
a { b:1; c:2; }
```

This rule does not parse correctly...

```css
a { b:1;c:2; }
```

...incorrectly resulting in the matched values `{b=1, [";c"]=2}`.
